name: Build

on:
  pull_request:
  push:
  release:
    types:
      - created

env:
  PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sdk_version:
          - '2.1.0'
          - '2.0.0'
          - '1.5.1'
    runs-on: ubuntu-latest
    steps:
    - name: Install ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '12.3.Rel1'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout pico-sdk
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        ref: ${{ matrix.sdk_version }}
        path: pico-sdk

    - name: Checkout TinyUSB
      run: |
        # checkout tinyusb in pico-sdk and switch to master branch
        git -C $PICO_SDK_PATH submodule update --init
        git -C $PICO_SDK_PATH/lib/tinyusb fetch
        git -C $PICO_SDK_PATH/lib/tinyusb checkout master

    - name: Build
      run: |
        cd examples
        mkdir build
        cd build
        cmake ..
        make

    - uses: actions/upload-artifact@v4
      with:
        name: example_binaries-sdk-${{ matrix.sdk_version }}
        path: |
          examples/build/usb_device/usb_device.uf2
          examples/build/usb_device/usb_device.hex
          examples/build/host_hid_to_device_cdc/host_hid_to_device_cdc.uf2
          examples/build/host_hid_to_device_cdc/host_hid_to_device_cdc.hex
